### ISSUE TITLE
Collect relational data from the LinkedIn account

### ISSUE THREAD

**Issue by DragonBe** [in2it-training/phpbootcamp-crm-talent-it-march-2017#20]
When retrieving the "member's information", see you can collect also the information of their LinkedIn relations and store them as additional contacts for the signed in member.

**Comment by thibaudpauwels** [comment]
Seems like this feature might not be possible . Linkedin does not give access to the 'relations' API anymore. They restricted is to linkedin partners only! https://developer.linkedin.com/support/developer-program-transition

**Comment by DragonBe** [comment]
See issue #25
