### ISSUE TITLE
Profile no picture -> bugged expecting picture

### ISSUE THREAD

**Issue by michielStaes** [in2it-training/phpbootcamp-crm-talent-it-march-2017#30]
![immagebug](https://cloud.githubusercontent.com/assets/26135526/23992444/443ed806-0a3d-11e7-93d0-0c811f3d03af.png)

**Comment by michielStaes** [comment]
Log in -> press on the contacts button -> this error occurs. (this profile has no picture)

**Comment by GijsPaulussen** [comment]
Go to MySQL workbench, truncate all tables in phpbootcamp_zfcrm except for the country table.
Run the server -> go to localhost:8000 -> delete cookies and try again.
